server:
  port: 8081
spring:
  application:
    name: kaspi
  profiles:
    active: dev


  datasource:
    url: jdbc:postgresql://localhost:5432/kaspi_db
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: kaspi-group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.kaspi

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.kaspi: DEBUG
    org.springframework.security: DEBUG

kaspi:
  notification:
    sms-template: "???? ?????? {{requestId}} ?????????? ? ?????? {{status}}."
security:
    jwt:
      secret: ${JWT_SECRET:Zm9vYmFyMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODk=}
      expiration: ${JWT_EXPIRATION_MS:3600000}
      refresh-expiration: ${JWT_REFRESH_MS:604800000}